const uuid = require('uuid');
const userstore = {};
/**
 * Expects a uuid value generated by this app.
 */
function check (userid){
  if (! userid || typeof(userid) !== 'string' ) return false;
  else return true;
}

function find(userid){
  if (check(userid)){
    const user = userstore[userid];
    if (user) return user;
  }
  return undefined;
}


function register(userid){
    if (check(userid)) {
       const user = userstore[userid];
       if (user) return user;
    }
    var newuser = {};
    newuser.id = uuid();
    userstore[newuser.id] = newuser;
    return newuser;
}

module.exports = {
  check: check,
  find: find,
  register: register
}
